import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { kiona, ttNorms } from "./fonts";
import { Header } from "@/components/ui/Header";
import "./globals.css";
import { Footer } from "@/components/ui/Footer";
import { Toaster } from 'react-hot-toast';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`
          ${geistSans.variable} 
          ${geistMono.variable} 
          ${kiona.variable} 
          ${ttNorms.variable} 
          antialiased
        `}
      >
        <Header />
        {children}
        <Footer />
        <Toaster 
          position="top-center"
          toastOptions={{
            duration: 3000,
            style: {
              background: '#333',
              color: '#fff',
            },
          }}
        />
      </body>
    </html>
  );
}
